// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendActivityLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DecryptFileInPlace(arg1:string,arg2:string):Promise<void>;

export function EncryptFileInPlace(arg1:string,arg2:string):Promise<main.EncryptionResult>;

export function GetClipboardText():Promise<string>;

export function PickFile():Promise<main.FileSelection>;

export function SetClipboardText(arg1:string):Promise<void>;
